apiVersion: v1
kind: Service
metadata:
  name: green-blog-co-service
  labels:
    app: green-blog-co
spec:
  ports:
    - port: 3000
      targetPort: 9000
      name: tcp
  selector:
    app: green-blog-co