apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: green-blog-co-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: green-blog-co
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70