apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: green-blog-co
images:
- name: 971490215356.dkr.ecr.ap-northeast-2.amazonaws.com/green-blog-co
  newTag: 285f130465b24f783dd63a444145d1d576f4f33a
resources:
- gateway.yaml
- virtual-service.yaml
- hpa.yaml
- ../base
