apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: green-blog-co
images:
- name: 971490215356.dkr.ecr.ap-northeast-2.amazonaws.com/green-blog-co
  newTag: 3d10aa5be39a948c87d28b10ee563f5479b272a8
resources:
- gateway.yaml
- virtual-service.yaml
- hpa.yaml
- ../base
