apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: green-blog-co
images:
- name: 971490215356.dkr.ecr.ap-northeast-2.amazonaws.com/green-blog-co
  newTag: ce6a1c69d17ce0fa549e51bec6621d9ebaeacfd1
resources:
- gateway.yaml
- virtual-service.yaml
- hpa.yaml
- ../base
